"""Liftover between human genomes for cpg positions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_liftover_pos.ipynb.

# %% auto 0
__all__ = ['cpg_content', 'func']

# %% ../nbs/03_liftover_pos.ipynb 12
def cpg_content(chromosomes: list, positions, ref_genome: Path, index_base = int):
    pass
    

# %% ../nbs/03_liftover_pos.ipynb 15
def func(): pass;
