"""Liftover between human genomes for cpg positions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_liftover_pos.ipynb.

# %% auto 0
__all__ = ['func']

# %% ../nbs/03_liftover_pos.ipynb 14
def func(): pass;
