"""Liftover between human genomes for cpg positions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_liftover_pos.ipynb.

# %% ../nbs/03_liftover_pos.ipynb 3
from __future__ import annotations

# %% auto 0
__all__ = ['cpg_reads', 'cpg_percent', 'guess_ref_and_index_base', 'liftover_positions']

# %% ../nbs/03_liftover_pos.ipynb 13
from typing import Sequence, Union

def cpg_reads(chromosomes: Sequence, positions: Sequence, ref_genome: 'Path | str | pysam.FastaFile', index_base: int = 1):
    """
    Fetch the 2bp sequence starting at each given genomic position from a reference genome.

    - chromosomes: list-like of chromosome names (e.g., 'chr1' or '1').
    - positions: list-like of genomic positions (ints). If index_base==1, positions are 1-based; if 0, 0-based.
    - ref_genome: genome name (e.g., 'hg19'), a path to a bgzipped FASTA, or an open pysam.FastaFile.
    - index_base: 0 or 1 (default: 1).

    Returns a pandas Series of the fetched 2-mer (uppercased). None when unavailable.
    Also tolerates 'chr' vs no 'chr' chromosome naming by resolving once per unique chromosome.
    """
    import pysam as _pysam
    import pandas as _pd
    from pathlib import Path as _Path
    from bs_cpg.download_ref import get_ref_genome


    # Normalize inputs
    chroms = list(chromosomes.tolist() if hasattr(chromosomes, 'tolist') else chromosomes)
    poss = list(positions.tolist() if hasattr(positions, 'tolist') else positions)
    
    if len(chroms) != len(poss):
        raise ValueError("chromosomes and positions must be the same length")

    # Determine index base
    base = 1
    if isinstance(index_base, (int, float)) and int(index_base) in (0, 1):
        base = int(index_base)
    elif isinstance(index_base, str) and index_base in ("0", "1"):
        base = int(index_base)

    # Resolve/open FASTA
    close_after = False
    if isinstance(ref_genome, _pysam.FastaFile):
        fasta = ref_genome
    else:
        rg_path = ref_genome
        # If a string/path that exists on disk, use as-is; otherwise treat as genome name
        if isinstance(rg_path, (str, _Path)):
            p = _Path(rg_path)
            if p.exists():
                fasta_path = p
            else:
                fasta_path = get_ref_genome(str(rg_path), verbose=False)
        else:
            fasta_path = get_ref_genome(str(rg_path), verbose=False)
        fasta = _pysam.FastaFile(str(fasta_path))
        close_after = True

    # Precompute available references and resolve aliases ('chr1' <-> '1') once per unique chrom
    try:
        ref_set = set(fasta.references)
    except Exception:
        ref_set = set()
    alias_map = {}
    uniq = {str(c) for c in chroms if c is not None and not (_pd.isna(c) if hasattr(_pd, 'isna') else False)}
    for s in uniq:
        cands = (s, (s[3:] if s.startswith('chr') else 'chr' + s))
        chosen = None
        for cand in cands:
            if cand in ref_set:
                chosen = cand
                break
        alias_map[s] = chosen

    out = []
    for chrom, pos in zip(chroms, poss):
        if chrom is None or _pd.isna(chrom) or pos is None or _pd.isna(pos):
            out.append(None)
            continue
        try:
            p = int(pos)
        except Exception:
            out.append(None)
            continue
        start = p - 1 if base == 1 else p
        if start < 0:
            start = 0
        alias = alias_map.get(str(chrom))
        if alias is None:
            out.append(None)
            continue
        try:
            seq = fasta.fetch(reference=str(alias), start=start, end=start + 2)
            out.append(seq.upper() if seq else None)
        except Exception:
            out.append(None)

    if close_after:
        fasta.close()

    return _pd.Series(out, name="cpg_reads")

# %% ../nbs/03_liftover_pos.ipynb 14
def cpg_percent(reads) -> float:
    """Return the percent of entries equal to 'CG' (case-insensitive) in `reads`.
    Accepts any iterable/Series; ignores NA/None.
    """
    import pandas as _pd
    if reads is None:
        return 0.0
    s = _pd.Series(reads)
    s = s.dropna().astype(str).str.upper()
    if len(s) == 0:
        return 0.0
    return 100.0 * (s == "CG").sum() / len(s)

# %% ../nbs/03_liftover_pos.ipynb 15
from typing import Sequence, Union, Dict, Any

def guess_ref_and_index_base(
    chromosomes,
    positions,
    ref_genomes: Sequence[Union[str, 'Path']],
    index_bases: Sequence[int] = (0, 1),
) -> Dict[str, Any]:
    """
    Try combinations of ref_genome and index_base, compute CG percent, and
    return the best guess (max percent) along with a summary of all tries.

    Returns a dict with keys: best_genome, best_index_base, best_percent, results (list of dicts).
    """
    from bs_cpg.download_ref import get_ref_genome
    results = []
    for rg in ref_genomes:
        # Resolve genome path string if a genome name was provided
        rg_path = rg
        if isinstance(rg, str):
            rg_path = get_ref_genome(rg, verbose=False)
        for base in index_bases:
            reads = cpg_reads(chromosomes, positions, rg_path, index_base=base)
            pct = cpg_percent(reads)
            results.append({
                "ref_genome": rg if isinstance(rg, str) else str(rg_path),
                "ref_genome_path": str(rg_path),
                "index_base": int(base),
                "percent_cg": float(pct),
            })
    # Pick max by percent_cg
    if results:
        best = max(results, key=lambda x: x["percent_cg"])
        return {
            "best_genome": best["ref_genome"],
            "best_index_base": best["index_base"],
            "best_percent": best["percent_cg"],
            "results": results,
        }
    return {"best_genome": None, "best_index_base": None, "best_percent": 0.0, "results": []}

# %% ../nbs/03_liftover_pos.ipynb 17
from typing import Sequence, Optional, Tuple, List, Union
import math

try:
    import pandas as _pd
except Exception:
    _pd = None

from liftover import ChainFile  # fast C++ liftover
from .download_ref import get_liftover_chain  # your helper


def liftover_positions(
    chromosomes: Sequence,
    positions: Sequence,
    genome_from: Optional[str] = None,
    genome_to: Optional[str] = None,
    index_base_from: int = 1,
    index_base_to: int = 1,
    return_df: bool = False,
) -> Union[Tuple[List[Optional[str]], List[Optional[int]]], "_pd.DataFrame"]:

    if len(chromosomes) != len(positions):
        raise ValueError(
            "Input sequences 'chromosomes' and 'positions' must be the same length."
        )

    # materialize sequences
    chroms = list(
        chromosomes.tolist() if hasattr(chromosomes, "tolist") else chromosomes
    )
    poss = list(positions.tolist() if hasattr(positions, "tolist") else positions)

    # normalize bases
    def _nb(x):
        if x in (0, 1, "0", "1"):
            return int(x)
        raise ValueError(f"Invalid index base '{x}'. Must be 0 or 1.")

    base_from = _nb(index_base_from)
    base_to = _nb(index_base_to)

    # hard-normalize types
    def _norm_chr(c):
        if c is None:
            return None
        s = str(c).strip()
        return s if s else None

    def _norm_pos(p):
        if p is None:
            return None
        if isinstance(p, float) and math.isnan(p):
            return None
        try:
            return int(p)
        except Exception:
            return None

    chroms = [_norm_chr(c) for c in chroms]
    poss = [_norm_pos(p) for p in poss]

    out_chroms: List[Optional[str]] = [None] * len(chroms)
    out_pos: List[Optional[int]] = [None] * len(poss)

    # Mode selection
    is_liftover = genome_from is not None and genome_to is not None
    if not is_liftover and not (genome_from is None and genome_to is None):
        raise ValueError(
            "Specify both 'genome_from' and 'genome_to' for liftover, or both None for base conversion."
        )

    if is_liftover:
        # Always use 0-based lifter to make math explicit.
        chain_path = get_liftover_chain(genome_from, genome_to, verbose=False)
        conv = ChainFile(str(chain_path), one_based=False)

        # helper to generate alias candidates per contig
        def _cands(c: str) -> List[str]:
            out = []
            if c.startswith("chr"):
                out += [c, c[3:]]
            else:
                out += [c, f"chr{c}"]
            if c in {"M", "MT", "chrM", "chrMT"}:
                out += ["M", "MT", "chrM", "chrMT"]
            # dedupe while preserving order
            seen, uniq = set(), []
            for x in out:
                if x not in seen:
                    seen.add(x)
                    uniq.append(x)
            return uniq

        for i, (c, p1) in enumerate(zip(chroms, poss)):
            if c is None or p1 is None:  # missing input
                continue
            # convert input to 0-based for the converter
            p0 = p1 - 1 if base_from == 1 else p1
            if p0 < 0:  # invalid in 0-based
                continue

            res_chrom = None
            res_pos0 = None
            for cand in _cands(c):
                try:
                    res = conv.convert_coordinate(
                        cand, p0
                    )  # [] if unmappable or contig absent
                except TypeError:
                    continue
                if res:
                    rc, rp0, *_ = res[0]
                    res_chrom, res_pos0 = rc, int(rp0)
                    break

            if res_chrom is None:
                continue  # unmapped

            # convert output base explicitly
            final_pos = res_pos0 + (1 if base_to == 1 else 0)
            if final_pos >= base_to:
                out_chroms[i] = res_chrom
                out_pos[i] = final_pos

    else:
        # simple base conversion only
        adj = base_to - base_from
        for i, (c, p) in enumerate(zip(chroms, poss)):
            if c is None or p is None:
                continue
            fp = p + adj
            if fp >= base_to:
                out_chroms[i] = c
                out_pos[i] = fp

    if return_df:
        if _pd is None:
            raise ImportError("pandas is required for `return_df=True`.")
        return _pd.DataFrame(
            {
                "chromosome_in": chroms,
                "pos_in": poss,
                "genome_from": genome_from,
                "genome_to": genome_to,
                "index_base_from": base_from,
                "index_base_to": base_to,
                "chromosome_out": out_chroms,
                "pos_out": out_pos,
            }
        )

    return out_chroms, out_pos
