"""Setup directories to store data."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_setup.ipynb.

# %% auto 0
__all__ = ['CONFIG_FILE', 'SUBDIR_NAME', 'get_base_data_path', 'func']

# %% ../nbs/01_setup.ipynb 5
from pathlib import Path
import os, json

# %% ../nbs/01_setup.ipynb 6
CONFIG_FILE = Path.home() / ".bs-cpg-config.json"
SUBDIR_NAME = ".bs-cpg"

def get_base_data_path():
    if CONFIG_FILE.exists():
        base = Path(json.loads(CONFIG_FILE.read_text())["base_path"]).expanduser()
    else:
        user_input = input("Where should .bs-cpg be stored (e.g. ~ or /mnt/data)? ")
        base = Path(user_input).expanduser().resolve()
        CONFIG_FILE.write_text(json.dumps({"base_path": str(base)}))
    
    final_path = base / SUBDIR_NAME
    final_path.mkdir(parents=True, exist_ok=True)
    return final_path

# %% ../nbs/01_setup.ipynb 7
get_base_data_path()

# %% ../nbs/01_setup.ipynb 8
def func(): pass;
