"""Download processed RRBS data. This is usually in BED format."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_download_processed.ipynb.

# %% auto 0
__all__ = ['memory', 'geof', 'Geofetcher']

# %% ../nbs/00_download_processed.ipynb 5
from geofetch import Geofetcher as OriginalGeofetcher
from tenacity import retry, wait_exponential, stop_after_attempt 
from joblib import Memory

memory = Memory(".cache", verbose=0)

# %% ../nbs/00_download_processed.ipynb 6
def _fetch_projects(*a, **kw):
    return OriginalGeofetcher().get_projects(*a, **kw)

_fetch_projects_retry = retry(
    wait=wait_exponential(multiplier=0.5, min=0.1, max=10),
    stop=stop_after_attempt(3),
    reraise=True
)(_fetch_projects)

_get_projects_cached = memory.cache(_fetch_projects_retry)

# %% ../nbs/00_download_processed.ipynb 7
class Geofetcher(OriginalGeofetcher):
    def get_projects(self, *a, ignore_cache=False, **kw):
        if ignore_cache:
            _get_projects_cached.clear()
            return _fetch_projects_retry(*a, **kw)
        return _get_projects_cached(*a, **kw)

# %% ../nbs/00_download_processed.ipynb 12
#|eval: false
geof=Geofetcher(processed=True, data_source="all", metadata_folder = f"/mnt/idms/home/magyary/sra-data/metadata/",
               name = acc)

# %% ../nbs/00_download_processed.ipynb 15
#|eval: false
projects_files['GSE51239_raw'].sample_table.iloc[:5,:]
