"""Setup directories to store data. Download reference genomes, chain files."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_setup.ipynb.

# %% auto 0
__all__ = ['func']

# %% ../nbs/02_setup.ipynb 5
from pathlib import Path
import os, json

# %% ../nbs/02_setup.ipynb 9
def func(): pass;
