name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BS_CPG_DATA: /tmp/bs-cpg-data
    steps:
      - uses: fastai/workflows/quarto-ghp@master
        with:
          nb_deps: "execnb"
